// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeModel } from "./ClaudeModel";
import type { Theme } from "./Theme";

export type Catalog = { models: Array<ClaudeModel>, themes: Array<Theme>, label_max_length: number, };
