// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderInfo } from "./ProviderInfo";
import type { Theme } from "./Theme";

export type Catalog = { providers: Array<ProviderInfo>, themes: Array<Theme>, label_max_length: number, };
