// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanupItem = { id: string, name: string, total: number, complete: boolean, protected: boolean, special: boolean, };
