// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "missingCredentials" | "invalidCredentials" | "notDesktopClient" | "loginTimeout" | "loginMismatch" | "loginDenied" | "noRefreshToken" | "tokenRejected" | "noSession" | "network" | "gmail" | "gmailBusy" | "aiUnavailable" | "aiFailed" | "aiKeyMissing" | "aiKeyRejected" | "invalidModel" | "invalidUrl" | "noUnsubscribe" | "unsubscribeFailed" | "invalidLabel" | "invalidSender" | "invalidId" | "invalidLocale" | "keyring" | "io" | "invalidData";
