// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Sender } from "./Sender";

export type Group = { label: string, is_new: boolean, action: Action, senders: Array<Sender>, };
