// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Phase = "searching" | "reading" | "thinking" | "applying" | "cleaning" | "done";
