// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Group } from "./Group";

export type Proposal = { read: number, failed: number, groups: Array<Group>, };
