// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type ProviderInfo = { provider: Provider, default_model: string | null, default_base_url: string | null, needs_key: boolean, accepts_key: boolean, custom_url: boolean, local: boolean, };
