// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSettings } from "./AiSettings";
import type { Theme } from "./Theme";

export type Settings = { ai: AiSettings, limit: number, cleanup_days: number, protected: Array<string>, theme: Theme, locale: string | null, };
