// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeModel } from "./ClaudeModel";
import type { Theme } from "./Theme";

export type Settings = { model: ClaudeModel, limit: number, cleanup_days: number, protected: Array<string>, theme: Theme, locale: string | null, };
