// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Unsubscribe } from "./Unsubscribe";

export type Subscription = { email: string, name: string, count: number, unread: number, unsubscribe: Unsubscribe, };
